### PR TITLE
Fix rendering of discounted unit price on invoice.

### LINKED ISSUE #1924: Discounted item info on invoice / quote
Issue linked to #1824. Yesterday I made an invoice using ospos and found a new column showing discount / item in the item table. This column also shows when there is no discount. I think it should not be the case as it confused me as it seemed that there was a discount.

### PR DESCRIPTION
**Pull request by SteveIreland**
This should close #1924 and #1958.

### CODE REVIEW

File: application/views/sales/invoice_email.php [hunk 1]
```diff
@@ -72,9 +72,16 @@
 			<th><?php echo $this->lang->line('sales_quantity'); ?></th>
 			<th><?php echo $this->lang->line('sales_price'); ?></th>
 			<th><?php echo $this->lang->line('sales_discount'); ?></th>
-			<?php if ($item['discount'] > 0): ?>
-			<th><?php echo $this->lang->line('sales_customer_discount');?></th>
-			<?php endif; ?>
+			<?php
+			$invoice_columns = 6;
```
Comment (jekkos) [inline application/views/sales/invoice_email.php]: It would have been more dynamic to fetch the number of columns in javascript and do adjustments there based on a class or label attached to each column.. but I guess this does the job
